# Generated by Django 5.2.3 on 2025-06-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status_pembayaran',
            field=models.BooleanField(default=False),
        ),
    ]
