# Generated by Django 5.2.3 on 2025-06-23 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_customuser_status_pembayaran_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='id',
        ),
        migrations.AlterField(
            model_name='billing',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
